auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: lwrrior
url: http://lwrrior.github.io
feed: /atom.xml
author_info: <a href="http://lwrrior.github.io/">lwarrior</a>
